# Generated by Django 4.1.1 on 2022-10-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('grade', models.CharField(max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=50)),
                ('idea', models.TextField()),
            ],
        ),
    ]
